language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly


install:
    # flags to pass to install
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    # install dependencies using system provided composer binary
    - composer install $flags
    # install dependencies using composer from source
    - bin/composer install $flags