language: php
php:
  - 7.1
  - 7.2
  - nightly


install:
    # install dependencies using system provided composer binary
    - composer install
    # install dependencies using composer from source
    - bin/composer install